### ISSUE TITLE
Add ability to highlight specific lines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#136]
```
It would be nice to have ability to highlight specific lines of code to catch 
viewer's attention (by changing background color for example).

Syntax could be <pre class="prettyprint highlight:10,20,30,40"></pre>

```

Original issue reported on code.google.com by `serg472@gmail.com` on 23 Dec 2010 at 10:41

**Comment by amroamroamro** [comment]
As mikesamuel suggested, here is an example of using CSS nth-child to highlight a specific line as well as a range of lines:

> https://jsfiddle.net/amroamroamro/535tw4bf/

**Comment by boukeas** [comment]
The example by @amroamroamro works only for prettified code that includes line numbers (i.e. the ``linenums`` class has been used), so it is not a general solution. 

But, more importantly, it seems to me that the code that needs to be highlighted should be highlighted in the HTML code, with CSS specifying only _how_ it is to be highlighted. So the <span> approach suggested earlier by @GoogleCodeExporter with ``<span>`` tagging seems more appropriate. In my case, I need to highlight code segments that get inserted and deleted, so I use the ``<ins>`` and ``<del>`` tags, instead of ``<span>``.

However, one problem is that ``<span>``s, ``<ins>``s and  ``<del>``s are inline elements and so only the code gets highlighted, not the whole line. If you display them with as  ``display: block``, the formatting _breaks_ (whitespace is inserted). I can't think of a simple solution that can do the trick of highlighting whole lines that are appropriately tagged, without using CSS hacks.
