### ISSUE TITLE
VB Script single Quote comment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#336]
```
Please see this jsfiddle for VB script , single quote comment is not working

http://jsfiddle.net/dekajp/27skU/1/

```

Original issue reported on code.google.com by `jdeka.re...@gmail.com` on 5 Mar 2014 at 4:17

**Comment by wolf99** [comment]
This is a very similar issue, if not the same on StackOverflows use of code-prettify.

See the comments in the code in the question at that appear as if they are unterminated strings http://stackoverflow.com/questions/33936054/no-console-output-from-memorystream-of-serialized-xml. When language is auto-detected the `'` used for the comments seems to start a string rather than a comment.

If language is specified using the hint `<!-- language: lang-vb -->` then only things in `<>` are highlighted (as stings) and *nothing* else

**Comment by thdoan** [comment]
This issue can be reproduced. Here's an example where the single quote trips up the syntax highlighting:

http://10basetom.tumblr.com/post/137272031416/excel-2007-vba-converting-accented-characters-to

Here's how I'm loading the script:
`<script src="//cdnjs.cloudflare.com/ajax/libs/prettify/r298/run_prettify.min.js?lang=vb"></script>`

**Comment by Phrancis** [comment]
We have also noticed this problem on Stack Exchange / Stack Overflow sites using Prettify. Here is an example post:

http://codereview.stackexchange.com/questions/126780/invisible-plots-after-running-a-macro-using-a-large-dataset

![2016-04-26 16_33_03-excel - invisible plots after running a macro using a large dataset - code revie](https://cloud.githubusercontent.com/assets/8539648/14834859/b454cf14-0bd4-11e6-907f-65e7339a72bc.png)

We noticed the regex parsing for comments in VBA works fine, it appears to be a problem where it is being caught by the multiline string matcher, there would need to possibly be a way to override this if the language is of VB family. 

![2016-04-26 16_40_58-regexr_ learn build test regex](https://cloud.githubusercontent.com/assets/8539648/14834866/c18276a0-0bd4-11e6-8f0a-ad72ba47e5ab.png)

**Comment by The-Quill** [comment]
Is there a valid usecase where a multi-line comment block is opened with a single quote?

Otherwise it could just be removed from [the global regex](https://github.com/google/code-prettify/blob/master/src/prettify.js#L900) entirely.

**Comment by thdoan** [comment]
@The-Quill I believe VBA doesn't have comment blocks -- every commented line has to start with a single quote.

**Comment by The-Quill** [comment]
@thdoan I was talking about the regex statement for comment blocks that applies when you don't specify a language. 

Going through [a list of comment structures](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_%28syntax%29#Comment_comparison) it doesn't look like any languages actually use single quotes for multi-line comment blocks

**Comment by thdoan** [comment]
@The-Quill Yeah I'm not aware of any either and would vote for that regex to be removed.

**Comment by Phrancis** [comment]
I have removed my comment because we have found the bug on Stack Exchange was due to not identifying the correct language. However, it would still be good to find a way to fix this...

**Comment by amroamroamro** [comment]
VB language is implemented using an extension `lang-vb.js`. You must include this script in your page, otherwise you get the default language handler (where the symbol `'` is not used to mark comments).

Here is a live version to show how `lang-vb` correctly highlights both examples posted here:
https://jsfiddle.net/amroamroamro/gf4n210p/1/

Note the URL in the "external resources" section, which uses the [autloader][1] to load both the core prettify script and vb lang extension.

[1]: https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader

**Comment by thdoan** [comment]
@amroamroamro  I am doing exactly the same as you -- the only difference is I'm loading `run_prettify.js` from [cdnjs.com](https://cdnjs.com/libraries/prettify) instead of the GitHub CDN.

It appears either of these could be the root cause:

1. It doesn't work when you load from `//cdnjs.cloudflare.com/ajax/libs/prettify/r298/run_prettify.js`
2. It doesn't work when the script is minified. Note that there is already `r298/run_prettify.min.js`, so why is `r298/run_prettify.js` also minified?

If either of these is the case, you should fix the `r298/run_prettify.js` version on cdnjs or remove it entirely.

**Comment by amroamroamro** [comment]
@thdoan 
I had a look, and seems that `run_prettify.js` has its [name hardcoded][4] inside the script, also it is [hardcoded to use RawGit][5] for loading additional extensions and skins.

> Please note that [RawGit CDN][3] is [not associated][2] with GitHub.
It used to be served directly from Google Code where the project was [hosted][7], but since it was retired, RawGit was chosen instead.

The idea is that it [looks][6] for `<script>` nodes inside the document from which it was loaded, and matches its `src` attribute against patterns like `run_prettify.js?lang=..&skin=..`. This is used to parse the [autoloader][1] options (like `autload=true` or `callback=myfunc`) as well as to figure out what additional extensions and stylesheets to load (`lang=vb` to load `lang-vb.js` and `skin=desert` to load `desert.css` theme). Keep in mind that there is no server side code here, which is why this hack was required to parse the URL.

So as it stands I'm afraid the run_prettify auto-loader scripts hosted on "cdnjs" are somewhat problematic:
1. the script named `run_prettify.min.js` is sorta broken and it will not load any extensions or skins (because it expects the name in the URL to be `run_prettify.js`).
2. `run_prettify.js` is already minified, there is no need for a separate .min.js file. Same goes for the other `lang-*.js` files.
3. `run_prettify.js` on cdnjs will work, but optional extensions/skins are still loaded from RawGit which defeats the purpose of using a different CDN
4. the version hosted on cdnjs is not the latest

Regarding point (1), I can see you've already reported this in another issue #419. I believe this can easily be fixed by recognizing an optional ".min" in the regex pattern.

Regarding point (2), I think there is a confusion regarding the project structure when they pulled the scripts to be hosted on CDNJS. `src/prettify.js` and `src/run_prettify.js` are generated (combined really) from files in `js-modules/*.js`. These generated files as well as the extensions in `src/lang-*.js` are the **un-minifed** versions. Then there are the **minifed** versions (produced with Google Closure Compiler) of those scripts inside `loader/*.js` (although they don't use the `.min.js` convention). Add to that the compressed version of `loader/` files (.zip, .tgz, .bz2) inside the `distrib/` folder. This is all done by the Makefile.

Regarding point (3), there is a PR #400 that suggested a fix so that it can be loaded from any host. The PR is a bit messy, but one should be able to reapply it cleanly on top of current master.

As for point (4), CDNJS is not to blame here.. code-prettify still doesn't use proper versions to tag releases. It's already been requested in #389 and other places.

Until run_prettify is fixed, you can always load the individual scripts yourself from CDNJS (`prettify.js`, `prettify.css` and any `lang-*.js` wanted), that will work and can be served from any host really. You just have to remember to call `PR.prettyPrint()` on page load (or DOM-ready event or whatever).

[1]: https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader
[2]: https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#is-rawgit-associated-with-github
[3]: https://rawgit.com/
[4]: https://github.com/google/code-prettify/blob/master/js-modules/run_prettify.js#L147
[5]: https://github.com/google/code-prettify/blob/master/js-modules/run_prettify.js#L179
[6]: https://github.com/google/code-prettify/blob/master/js-modules/run_prettify.js#L138
[7]: https://code.google.com/archive/p/google-code-prettify/

**Comment by thdoan** [comment]
@amroamroamro Thanks for the detailed response -- I will use your suggestion to load the file individually instead of using the auto-loader.
