### ISSUE TITLE
Fails with Scala triple-quoted string containing quote(s) inside

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#342]
```
Consider this Scala snippet:

val txt = """This text has "quoted" text on it""" + otherString

The quotes inside the triple-quoted string should not unquote or confuse the 
parsing.

The entire tripe-quoted string should be formatted as if it was a single-quoted 
string with nothing fancy on them.

In other words: the quotes inside a triple-quoted string should not need to be 
escaped (because, in Scala, they don't need to; that's the point).
```

Original issue reported on code.google.com by `sebno...@gmail.com` on 15 May 2014 at 11:02

Attachments:
- [tripple-quoted-bug.png](https://storage.googleapis.com/google-code-attachments/google-code-prettify/issue-342/comment-0/tripple-quoted-bug.png)

**Comment by amroamroamro** [comment]
Scala in code-prettify is implemented as an extension `lang-scala.js`, and you must explicitly include this script in your page, otherwise you get the default generic language handler (C-like lang that does not accept triple-quoted strings)..

Here is an example to show it is highlighted correctly when `lang-scala.js` is properly loaded:
https://jsfiddle.net/amroamroamro/wdxgwnsz/

Pay attention to the URL in the "External Resources" (the [auto-loader][1] script).

[1]: https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader
