### ISSUE TITLE
Problem with backslash in VB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/code-prettify#365]
```
What steps will reproduce the problem?
1. Create <pre> element with some vb code and place a backslash within double 
quotes

Eg.

<pre name="code" class="prettyprint lang-vb">
Sub Test()
    Print "path\filename"
End Sub
</pre>

The backslash is treated as escape character so all the code next to the 
backslash is treated as string content, when it is not: string content must end 
with the last double quote at the end of the same line.


```

Original issue reported on code.google.com by `massimo....@gmail.com` on 22 Jan 2015 at 7:55

Attachments:
- [Screenshot_1.png](https://storage.googleapis.com/google-code-attachments/google-code-prettify/issue-365/comment-0/Screenshot_1.png)

**Comment by amroamroamro** [comment]
VB language is implemented as an extension `lang-vb.js`, and you must explicitly include that script in your page, otherwise you get the default language handler (which treats `\` as escape inside a string)..

Here is an example to show it is highlighted correctly when `lang-vb` is properly loaded:

> https://jsfiddle.net/amroamroamro/m7g0sfmk/

Pay attention to the URL in the "External Resources" (I'm using the [auto-loader][1]).

[1]: https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader
