### ISSUE TITLE
adding tags for the repo

### ISSUE THREAD

**Issue by Amomo** [google/code-prettify#389]
Hello, 

Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example it could be hosted by [cdnjs](https://github.com/cdnjs/cdnjs) ([website](https://cdnjs.com/))

Would you please consider on using tags?
Thanks for your great work!

**Comment by mikesamuel** [comment]
amroamroamro, thanks for doing all that.  

I'm horribly ignorant of git internals, but I think commit identifiers and tags are based on hashes of branch state.

If so, the hashes in amroamroamro/code-prettify/tags
should line up with the hashes in google/code-prettify making it fairly simple to reproduce your work.

Do you know if that's the case?

**Comment by amroamroamro** [comment]
yes, a [tag][1] in git is simply a pointer to a specific commit.

The way git [internally][2] manages lightweight tags is that it stores SHA-1 checksums of commits in a text file (either one-file-per-ref under `.git/refs/tags/`, or all combined in one file `.git/packed-refs` for efficiency).

One the other hand, annotated tags are much like regular commit objects stored in the git database (they carry more information like author and date and can be cryptographically signed and verified).

Here are the tags I created:
```
$ git show-ref --tags -d
ca84bd1fe27748a93ffb65791e062b590517e6ed refs/tags/release-2-Apr-2007
81a8ec22194b44ff37e066b04b22c0967d0bba06 refs/tags/release-22-May-2007
565f704c417dff497294ec82f2e05499e9900a95 refs/tags/release-31-Aug-2007
fb8183660a522c49a0b4c5684b821bdf674b97b9 refs/tags/release-4-Jul-2008
6f4a2d6701f2b94c00ac704d4dace0634475dccb refs/tags/release-5-Jul-2008
60cf2e0e165b8269fb4b2a1a2dafa969e4bd6f71 refs/tags/release-14-Jul-2008
6c989238dbb40cbf6d09fee42044c148496ca301 refs/tags/release-8-Jan-2009
bb9db834e4e90152de473c186416ff58711637a0 refs/tags/release-21-May-2009
2af3a2ed4a985d1f24ea3afedf9885e658004eed refs/tags/release-3-Dec-2009
ed2bf56c00ff71b18e7581b47cd2c5fbcd1b00bf refs/tags/release-21-Jul-2010
f1d86b2ba8457e7702881d0fae2d98598303ac7f refs/tags/release-1-Jun-2011
7819105327a51a4b72618b86926a13636c4186a4 refs/tags/release-10-Feb-2013
f5972ab29d1920f42b9d62bf0727fcfb27a6e62e refs/tags/release-23-Feb-2013
4f16682c53ea98ea02f7454b6320df8a9f492438 refs/tags/release-25-Feb-2013
12a278337b7710ddba374cf41b410d1bdedbdd3e refs/tags/release-4-Mar-2013
22815944f9a5b6b7f5529ce27718103eb5c1ad7d refs/tags/release-21-Jun-2013
```

[1]: https://git-scm.com/book/en/v2/Git-Basics-Tagging
[2]: http://stackoverflow.com/a/25996877/97160

**Comment by amroamroamro** [comment]
@mikesamuel 
I recently picked up [prettify-matlab](https://github.com/amroamroamro/prettify-matlab) again to give it some updates (I changed the build system to Node.js/Grunt among other things).

A bit late now but since I have access here, if it's alright with you, I'm willing to help with the above issue creating the tags and adding the releases ?

I also have some other fixes, for which I'll create a pull-request for review.

**Comment by amroamroamro** [comment]
I've since replicated the above in this repo. [Tags](https://github.com/google/code-prettify/tags) were created and named as `yyyy-mm-dd`. I also added [releases](https://github.com/google/code-prettify/releases) using the [downloads](https://code.google.com/p/google-code-prettify/downloads/list?can=1) from the old SVN repo.
