### ISSUE TITLE
JSDoc prettyprint's plain text markdown, adding colors

### ISSUE THREAD

**Issue by lll000111** [google/code-prettify#495]
JSDoc owner said: 

> This sounds like a bug in our pretty-printing library. Please file a bug against that repo.

See https://github.com/jsdoc3/jsdoc/issues/1361

----

I have this JSDoc (excerpt) for a function:

```javascript
/**
 *....
 * Circle detection is not implemented, you simply get a
 * ```plain
 * RangeError: Maximum call stack size exceeded
 * ```
 * exception.
 *....
 */
```

This becomes what you see in the screenshot below, colorful text that is anything but "plain" (I also tried leaving out a code type string or using `text`, same results):

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![screenshot-1](https://cloud.githubusercontent.com/assets/25476357/25780536/cb49f42a-3328-11e7-9846-97bd708bc8e5.png)

<br>

What is there to "pretty-print" in plain text?

<br>

**Comment by mikesamuel** [comment]
Is there a language handler for lang-plain loaded?

**Comment by lll000111** [comment]
I don't know what that means and/or what to look at/for...

**Comment by mikesamuel** [comment]
The `class="lang-plain"` bit will only have an effect if there is a language handler registered by that name.

The convention used by this project is that `lang-` followed by the commonly accepted file extension is used.  Since plain text files are usually called *filename*`.txt`, `class="lang-txt"` would specify plain text.

There's no such handler provided by default though.  Usually people who want code not prettified, just don't put `class="prettyprint"` on the code block.

You can always add `class="prettyprint prettyprinted"` since the prettyprinter does not reenter blocks with the `prettyprinted` class.

**Comment by lll000111** [comment]
So... I read this that this is a usage problem and the ticket should indeed go to the JSdoc project?

**Comment by mikesamuel** [comment]
Yes, maybe mention that since prettify uses file extensions and markdown source blocks tend to use descriptive language names, they probably have a table somewhere like

| languageName | prettifyClass |
| --------------- | ------------ |
| ada                     | lang-ada |
| bash                  | lang-sh |
| c++                    | lang-cpp |
| ...                        | ... |
| zsh                    | lang-sh |

and adding an entry like

| languageName | prettifyClass |
| --------------- | ------------ |
| ...      | ... |
| plain | prettified |

would probably address the problem.
