### ISSUE TITLE
Can't type angle brackets in Markdown

### ISSUE THREAD

**Issue by philectron** [google/code-prettify#519]
I'm using Jekyll 3.5.2.

When I typed

```markdown
This line is outside of the code portion

<?prettify?>
<pre class="prettyprint cpp-html linenums">
int main(void) {
    std::cout << "Hello" << std::endl;
    return 0;
}
</pre>

This line is outside of the code portion
```

Then Prettify correctly highlighted my code:

![correct-highlight](https://i.imgur.com/oIWXZOC.png)

---

However, when I typed any angle brackets (`<` or `>`),

```markdown
This line is outside of the code portion

<?prettify?>
<pre class="prettyprint cpp-html linenums">
#include <iostream>

int main(void) {
    std::cout << "Hello" << std::endl;
    return 0;
}
</pre>

This line is outside of the code portion
```

Then Prettify messed up:

![incorrect-highlight](https://i.imgur.com/UavmyoF.png)

---

I believe Prettify thought `<iostream>` was an HTML tag and so accidentally messed things up from there. Is that because I used the tags incorrectly or because of the way Markdown works? How do we fix this issue?

**Comment by danyvs** [comment]
It may not the solution you are looking for, but I solved this problem by using "iostream" instead <iostream>

**Comment by amroamroamro** [comment]
First of all, code-prettify runs in the browser so a page must be valid HTML to begin with. That means at minimum, you have to encode all literal `<`, `>`, and `&` characters using `&lt;`, `&gt;`, and `&amp;` respectively:

    <pre class="prettyprint lang-cpp linenums">
    #include &lt;iostream&gt;
    int main(void) {
        std::cout &lt;&lt; "Hello" &lt;&lt; std::endl;
        return 0;
    }
    </pre>


You mentioned Markdown, there is none involved here so far, this is plain old HTML.

If you were writing in Markdown, you would use indentation like:

    This line is outside of the code portion

        #include <iostream>
        int main(void) {
            std::cout << "Hello" << std::endl;
            return 0;
        }

    This line is outside of the code portion

or using backticks (Github flavor):

    This line is outside of the code portion

    ```cpp
    #include <iostream>
    int main(void) {
        std::cout << "Hello" << std::endl;
        return 0;
    }
    ```

    This line is outside of the code portion

or as you did with embedded HTML (but correctly escaped using HTML entities):

    This line is outside of the code portion

    <?prettify?>
    <pre class="prettyprint lang-cpp linenums">
    #include &lt;iostream&gt;
    int main(void) {
        std::cout &lt;&lt; "Hello" &lt;&lt; std::endl;
        return 0;
    }
    </pre>

    This line is outside of the code portion

In the first two, the markdown engine takes care of escaping special chars before wrapping the snippet inside a PRE tag. In the latter with embedded HTML, you have to do it manually.

---

Jekyll being a static website generator has builtin support for syntax highlighting:

> https://jekyllrb.com/docs/templates/#code-snippet-highlighting

You have to use the special template syntax shown.

According to the docs, you have two choices either Rouge (Ruby library) or Pygments (Python library), obviously both running offline when generating the site.

Otherwise if you still want to use code-prettify (applied live in the browser), use the third example above.

**Comment by philectron** [comment]
@amroamroamro Thanks for pointing out the solution where I need to encode `<` and `>`.

Actually, Prettify only got messed up when it came to single angle brackets (`<` and `>`), which were probably mistaken with HTML tags. Other special characters have been working so far.

I fixed the problem by adding a `<span>` for each angle bracket:

**SOLUTION**

```
This line is outside of the code portion

<?prettify?>
<pre class="prettyprint cpp-html linenums">
#include <span><</span>iostream<span>></span>

int main(void) {
    std::cout << "Hello" << std::endl;
    return 0;
}
</pre>

This line is outside of the code portion
```

But I think your solution is better because yours looks a lot cleaner than mine.

**BETTER SOLUTION**

```
This line is outside of the code portion

<?prettify?>
<pre class="prettyprint cpp-html linenums">
#include &lt;iostream&gt;

int main(void) {
    std::cout << "Hello" << std::endl;
    return 0;
}
</pre>

This line is outside of the code portion
```

Thanks a lot for the help! Prettify is awesome!
