### ISSUE TITLE
repo has dependencies on rawgit, which is shutting down

### ISSUE THREAD

**Issue by erood** [google/code-prettify#564]
Rawgit is shutting down around October 2019 [1], and Prettify has dependencies on the site (even if self-hosting the core files, since run_prettify.js relies on it in several areas). Are there plans to transition to a different service?

[1] https://rawgit.com/

**Comment by hifocus** [comment]
Just found out the same problem. And I think Rawgit is more likely to be a personal service (it is as it mentioned in its home page), so Google should not use a personal service in a public project.

**Comment by blanks27** [comment]
as seen on a simulator screen I found a glitch on a blue jay or something like blue jay mobile phone I don't think I got credited with thus bring me to why html and [pm] screens is known thus also meaning am a techy geeking ksi losers mlg wankstas and I crushed sum of your gibsons on halo two and beat moddeers on halo 2 xbox 360 also found a assaisions creed 2 glitch witch I almost pulled out of but was held by sum hy[per flex

**Comment by ncruces** [comment]
@zwetan, you are of course correct.

Can you have a look at #573, and see if it fixes this?

Feel free to use the following until something better is merged:
https://cdn.jsdelivr.net/gh/ncruces/code-prettify@master/loader/run_prettify.js

**Comment by mikesamuel** [comment]
Sorry I haven't been involved in the rawgit turndown.

1. Pick a jsDelivr URL.  https://github.com/google/code-prettify/issues/564#issuecomment-437964430
2. Change internal uses of rawgit to be consistent with 1.
3. Merge 2 into master.
4. Update documentation.

It seems like there's no gap between committing and changes being visible on jsDelivr that would cause problems for newish HTML pages that want to embed jsdelivr URLs.

It's unclear to me how this would cause worse problems for HTML pages that embed rawgit URLs.  Anything come to mind?

**Comment by ncruces** [comment]
@mikesamuel, sorry if I didn't understand the question.
I tried to do just that (points 1-4) in #573.

I don't use jsDelivr for documentation because of [this](https://raw.githack.com/#why). So, for example:
https://raw.githack.com/google/code-prettify/master/examples/quine.html **(works)**
https://cdn.jsdelivr.net/gh/google/code-prettify@master/examples/quine.html **(doesn't work)**

But for the JS, it seems to me, jsDelivr is the way to go, thanks to its backing.
#573 discusses this, and I believe fixes all references, in code, documentation, and generated code.

**Comment by mikesamuel** [comment]
@ncruces Thanks for putting that together.  Will comment on #573.

**Comment by blanks27** [comment]
I'm not having access to reading rss feeds the links ain't there for me because I was to nosey they sayOn Dec 17, 2018 10:23 AM, Mike Samuel <notifications@github.com> wrote:Sorry I haven't been involved in the rawgit turndown.
Pick a jsDelivr URL.  #564 (comment)Change internal uses of rawgit to be consistent with 1.Merge 2 into master.Update documentation.
It seems like there's no gap between committing and changes being visible on jsDelivr that would cause problems for newish HTML pages that want to embed jsdelivr URLs.
It's unclear to me how this would cause worse problems for HTML pages that embed rawgit URLs.  Anything come to mind?
